name: Unit tests

on: 
  push:
    branches:
      - test
  pull_request:
    branches:
      - test
     

jobs:
  test:
    runs-on: ubuntu-latest 
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
          
      - name: Run Unit Tests
        run: python test.py
        continue-on-error: ${{ matrix.os == 'ubuntu-latest' }}
